project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "stoneyBrosGaming"
  favicon: sbg_round_Avatar.png
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/@stoneybrosgaming
        
format:
  html:
    theme: vapor
    css: styles.css


