project:
  type: website
  resources: 
    - "CNAME"
    
website:
  title: "stoneyBrosGaming"
  navbar:
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/@stoneybrosgaming
        
format:
  html:
    theme: vapor
    css: styles.css


