project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "stoneyBrosGaming"
  site-url: https://www.stoneybrosgaming.com
  description: "Try. Fail. Learn."
  favicon: sbg_round_Avatar.png
  open-graph: true
  navbar:
    right:
      - about.qmd
      - text: More Stuff
        menu:
          - merch.qmd
          - gallery.qmd
      - icon: youtube
        href: https://www.youtube.com/@stoneybrosgaming
      - icon: rss
        href: index.xml

        
format:
  html:
    theme: vapor
    css: styles.css
